### PR TITLE
Added Simplified Chinese Localization

### PR DESCRIPTION
**Pull request by Samekichi**

### CODE REVIEW

**Comment by PotatoPresident** [comment]
Also ran them through google real quick. Could be completely wrong, but it said the second one was "Need to right-click", but its actually about needing your hand to be empty when you right click. 

Didn't expect anyone to contribute. Thanks for donating your time to my little mod.

**Comment by Samekichi** [comment]
> Just added 2 more translatable texts.
> Could you do those as well? Thanks!

Done!

**Comment by PotatoPresident** [comment]
Awesome! Thanks!

**Comment by PotatoPresident** [comment]
I'm doing a major refactor and most of the translations have been removed/changed. If your interested in updating them [here are the new translations](https://github.com/PotatoPresident/PetOwner/blob/major_refactor/src/main/resources/assets/petowner/lang/en_us.json).

**Pull request merged**
